server:
  port: 3344
spring:
  application:
    name: cloud-config-center #微服务名称
  cloud:
    config:
      server:
        git:
          uri: https://github.com/XiaoFan-new/springcloud-config.git #GitHub上面的git仓库名称
          #搜索目录
          search-paths:
            - springcloud-config
      #读取分支
      label: master
  #RabbitMQ相关配置
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/ #单机版

##RabbitMQ相关配置，暴露Bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
